### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by Evavic44** [oscafrica/open-source-challenge-2021#2]
At the end of the README page, There is a typo on the following text. 

Contributing

### Issue
Found `an` very useful open source guide or resource? Kindly send a pull request and follow the contributors guidelines.

### Suggested changes
Found a very useful open source guide or resource? Kindly send a pull request and follow the contributors guidelines.

I can quickly fix this if you want.

**Comment by BolajiAyodeji** [comment]
Hi @Evavic44, thanks for submitting this issue.

I think someone else already fixed this and since apologies for the delayed response.

Next time you can go ahead to send a pull request for minor issues like this but it's a good habit to always ask (depending on the project's contributing guide) before you work on a contribution so you don't work on what would not be needed.

Great work!

**Comment by Evavic44** [comment]
🥲 It is well. Thank you.
